version: '2'  
services:  
  app:
    build:
      context: ./app
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
  
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
