# `my_api.yaml` file contents
swagger: '2.0'
info:
  title: test project API
  version: "0.1"
paths:
  /notes:
    get:
      operationId: app.test
      summary: test api call.
      responses:
        200:
          description: Successful response.
          schema:
            type: object
            properties:
              message:
                type: string
                description: test validation
